{{- if .Values.combinedDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llamator.fullname" . }}-api
  namespace: {{ include "llamator.namespace" . }}
  labels:
    {{- include "llamator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
  selector:
    app: {{ include "llamator.fullname" . }}-app
{{- end }}

