{{- if .Values.vault.enabled }}
---
# ExternalSecret for OpenAI API Keys
# Creates a Kubernetes Secret from Vault using External Secrets Operator
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-openai-es
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  # How often to sync secrets from Vault
  refreshInterval: {{ .Values.vault.refreshInterval | default "1m" }}

  # Reference to SecretStore or ClusterSecretStore
  secretStoreRef:
    kind: {{ .Values.vault.secretStoreKind | default "SecretStore" }}
    name: {{ .Values.vault.secretStoreRef | default "vault-team11" }}

  # Target Kubernetes Secret configuration
  target:
    name: {{ .Values.security.openai.attack.secret.name }}
    creationPolicy: Owner

  # Map Vault secret to Kubernetes Secret keys
  # All keys use the same OPENAI_API_KEY from Vault
  data:
    # Attack model API key
    - secretKey: {{ .Values.security.openai.attack.secret.key }}
      remoteRef:
        key: {{ .Values.vault.remoteRef.openai.key }}
        property: {{ .Values.vault.remoteRef.openai.property }}

    # Judge model API key
    - secretKey: {{ .Values.security.openai.judge.secret.key }}
      remoteRef:
        key: {{ .Values.vault.remoteRef.openai.key }}
        property: {{ .Values.vault.remoteRef.openai.property }}

    # Target model API key
    - secretKey: {{ .Values.security.openai.target.secret.key }}
      remoteRef:
        key: {{ .Values.vault.remoteRef.openai.key }}
        property: {{ .Values.vault.remoteRef.openai.property }}

{{- if .Values.security.apiKey.enabled }}
---
# ExternalSecret for API Key (client authentication)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-api-key-es
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  # How often to sync secrets from Vault
  refreshInterval: {{ .Values.vault.refreshInterval | default "1m" }}

  # Reference to SecretStore or ClusterSecretStore
  secretStoreRef:
    kind: {{ .Values.vault.secretStoreKind | default "SecretStore" }}
    name: {{ .Values.vault.secretStoreRef | default "vault-team11" }}

  # Target Kubernetes Secret configuration
  target:
    name: {{ .Values.security.apiKey.existingSecret }}
    creationPolicy: Owner

  # Map Vault secret to Kubernetes Secret key
  data:
    - secretKey: {{ .Values.security.apiKey.secretKey }}
      remoteRef:
        key: {{ .Values.vault.remoteRef.api.key }}
        property: {{ .Values.vault.remoteRef.api.property }}
{{- end }}

{{- if .Values.storage.s3.enabled }}
---
# ExternalSecret for S3 Storage credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-s3-keys-es
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  # How often to sync secrets from Vault
  refreshInterval: {{ .Values.vault.refreshInterval | default "1m" }}

  # Reference to SecretStore or ClusterSecretStore
  secretStoreRef:
    kind: {{ .Values.vault.secretStoreKind | default "SecretStore" }}
    name: {{ .Values.vault.secretStoreRef | default "vault-team11" }}

  # Target Kubernetes Secret configuration
  target:
    name: {{ .Values.storage.s3.existingSecret }}
    creationPolicy: Owner

  # Map Vault secrets to Kubernetes Secret keys
  data:
    - secretKey: {{ .Values.storage.s3.accessKeyIdKey }}
      remoteRef:
        key: {{ .Values.vault.remoteRef.s3.key }}
        property: {{ .Values.vault.remoteRef.s3.accessKeyIdProperty }}
    - secretKey: {{ .Values.storage.s3.secretAccessKeyKey }}
      remoteRef:
        key: {{ .Values.vault.remoteRef.s3.key }}
        property: {{ .Values.vault.remoteRef.s3.secretAccessKeyProperty }}
{{- end }}

{{- end }}