{{- if .Values.externalSecrets.enabled }}
---
# ExternalSecret для OpenAI API Keys
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-openai-keys
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.security.openai.attack.secret.name }}
    creationPolicy: Owner
  data:
    # Маппинг ключей из Vault в K8s Secret
    # Все три провайдера используют один API ключ из Vault
    - secretKey: {{ .Values.security.openai.attack.secret.key }}
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}/openai
        property: OPENAI_API_KEY
    - secretKey: {{ .Values.security.openai.judge.secret.key }}
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}/openai
        property: OPENAI_API_KEY
    - secretKey: {{ .Values.security.openai.target.secret.key }}
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}/openai
        property: OPENAI_API_KEY

{{- if .Values.security.apiKey.enabled }}
---
# ExternalSecret для API Key (аутентификация клиентов)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-api-key
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.security.apiKey.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.security.apiKey.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}/api
        property: API_KEY
{{- end }}

{{- if .Values.storage.s3.enabled }}
---
# ExternalSecret для S3 Storage credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-s3-keys
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.storage.s3.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.storage.s3.accessKeyIdKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}/s3
        property: ACCESS_KEY_ID
    - secretKey: {{ .Values.storage.s3.secretAccessKeyKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPath }}/s3
        property: SECRET_ACCESS_KEY
{{- end }}

{{- end }}

