{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-role
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

