# This is an EXAMPLE file showing the structure of secrets needed.
# DO NOT use this in production! Create secrets manually or use sealed-secrets/Vault.
#
# To create secrets manually:
#
# 1. Create OpenAI API keys secret:
# kubectl create secret generic llamator-openai-keys \
#   --from-literal=LLAMATOR_MCP_ATTACK_OPENAI_API_KEY='YOUR_ATTACK_API_KEY' \
#   --from-literal=LLAMATOR_MCP_JUDGE_OPENAI_API_KEY='YOUR_JUDGE_API_KEY' \
#   --from-literal=LLAMATOR_MCP_TARGET_OPENAI_API_KEY='YOUR_TARGET_API_KEY' \
#   --namespace llamator-mcp
#
# 2. Create API key secret (if enabled):
# kubectl create secret generic llamator-api-key \
#   --from-literal=LLAMATOR_MCP_API_KEY='YOUR_SECURE_API_KEY' \
#   --namespace llamator-mcp
#
# 3. Create S3 storage secret (if enabled):
# kubectl create secret generic llamator-s3-keys \
#   --from-literal=S3_ACCESS_KEY_ID='YOUR_S3_ACCESS_KEY_ID' \
#   --from-literal=S3_ACCESS_KEY='YOUR_S3_SECRET_ACCESS_KEY' \
#   --namespace llamator-mcp
#
# 4. For production, consider using:
#    - Sealed Secrets: https://github.com/bitnami-labs/sealed-secrets
#    - External Secrets Operator: https://external-secrets.io/
#    - HashiCorp Vault: https://www.vaultproject.io/
#    - Cloud provider secret managers (AWS Secrets Manager, Azure Key Vault, GCP Secret Manager)

{{- if .Values.security.createExampleSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.openai.attack.secret.name }}
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{ .Values.security.openai.attack.secret.key }}: "REPLACE_WITH_REAL_KEY"
  {{ .Values.security.openai.judge.secret.key }}: "REPLACE_WITH_REAL_KEY"
  {{ .Values.security.openai.target.secret.key }}: "REPLACE_WITH_REAL_KEY"

---
{{- if .Values.security.apiKey.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.apiKey.existingSecret }}
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{ .Values.security.apiKey.secretKey }}: "REPLACE_WITH_SECURE_API_KEY"
{{- end }}

---
{{- if .Values.storage.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.s3.existingSecret }}
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{ .Values.storage.s3.accessKeyIdKey }}: "REPLACE_WITH_S3_ACCESS_KEY_ID"
  {{ .Values.storage.s3.secretAccessKeyKey }}: "REPLACE_WITH_S3_SECRET_ACCESS_KEY"
{{- end }}
{{- end }}

