{{- if .Values.vault.enabled }}
{{- if .Values.vault.vaultSecretsOperator.enabled }}
---
# VaultAuth для Vault Secrets Operator
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-vault-auth
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.vault.vaultSecretsOperator.authMount "kubernetes" }}
  # Kubernetes auth method
  method: kubernetes
  mount: {{ .Values.vault.vaultSecretsOperator.authMountPath | default "kubernetes" }}
  kubernetes:
    role: {{ .Values.vault.vaultSecretsOperator.role }}
    serviceAccount: {{ include "llamator-mcp.serviceAccountName" . }}
    audiences:
      - vault
  {{- else if eq .Values.vault.vaultSecretsOperator.authMount "jwt" }}
  # JWT auth method
  method: jwt
  mount: {{ .Values.vault.vaultSecretsOperator.authMountPath | default "jwt" }}
  jwt:
    role: {{ .Values.vault.vaultSecretsOperator.role }}
    serviceAccount: {{ include "llamator-mcp.serviceAccountName" . }}
    audiences:
      - vault
  {{- else if eq .Values.vault.vaultSecretsOperator.authMount "appRole" }}
  # AppRole auth method
  method: appRole
  mount: {{ .Values.vault.vaultSecretsOperator.authMountPath | default "approle" }}
  appRole:
    roleId: {{ .Values.vault.vaultSecretsOperator.appRole.roleId }}
    secretRef:
      name: {{ .Values.vault.vaultSecretsOperator.appRole.secretRef | default "vault-approle-secret" }}
      key: {{ .Values.vault.vaultSecretsOperator.appRole.secretKey | default "secret-id" }}
  {{- else }}
  {{- fail (printf "Unsupported vault.vaultSecretsOperator.authMount: %s. Supported values: kubernetes, jwt, appRole" .Values.vault.vaultSecretsOperator.authMount) }}
  {{- end }}
  vaultConnectionRef: {{ .Values.vault.vaultSecretsOperator.vaultConnectionRef }}
{{- end }}
{{- end }}

