{{- if .Values.vault.enabled }}
{{- if .Values.vault.vaultSecretsOperator.enabled }}
{{- if .Values.security.openai.enabled }}
---
# VaultStaticSecret для OpenAI API Keys
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-openai-keys
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.vaultSecretsOperator.mount }}
  path: {{ .Values.vault.vaultSecretsOperator.secretPath }}/openai
  
  # Частота обновления секрета из Vault
  refreshAfter: {{ .Values.vault.vaultSecretsOperator.refreshAfter }}
  
  # Destination: создаем Kubernetes Secret
  destination:
    name: {{ .Values.security.openai.attack.secret.name }}
    create: true
    labels:
      managed-by: vault-secrets-operator
  
  # Rollout restart для Deployments при обновлении секрета
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "llamator-mcp.api.fullname" . }}
    - kind: Deployment
      name: {{ include "llamator-mcp.worker.fullname" . }}
  
  # Ссылка на VaultAuth
  vaultAuthRef: {{ include "llamator-mcp.fullname" . }}-vault-auth
{{- end }}

---
{{- if .Values.security.apiKey.enabled }}
# VaultStaticSecret для API Key
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-api-key
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.vaultSecretsOperator.mount }}
  path: {{ .Values.vault.vaultSecretsOperator.secretPath }}/api
  
  refreshAfter: {{ .Values.vault.vaultSecretsOperator.refreshAfter }}
  
  destination:
    name: {{ .Values.security.apiKey.existingSecret }}
    create: true
    labels:
      managed-by: vault-secrets-operator
  
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "llamator-mcp.api.fullname" . }}
  
  vaultAuthRef: {{ include "llamator-mcp.fullname" . }}-vault-auth
{{- end }}

{{- if and .Values.vault.enabled .Values.vault.vaultSecretsOperator.enabled .Values.storage.s3.enabled }}
---
# VaultStaticSecret для S3 Storage
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "llamator-mcp.fullname" . }}-s3-keys
  namespace: {{ include "llamator-mcp.namespace" . }}
  labels:
    {{- include "llamator-mcp.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.vaultSecretsOperator.mount }}
  path: {{ .Values.vault.vaultSecretsOperator.secretPath }}/s3
  
  refreshAfter: {{ .Values.vault.vaultSecretsOperator.refreshAfter }}
  
  destination:
    name: {{ .Values.storage.s3.existingSecret }}
    create: true
    labels:
      managed-by: vault-secrets-operator
  
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "llamator-mcp.api.fullname" . }}
    - kind: Deployment
      name: {{ include "llamator-mcp.worker.fullname" . }}
  
  vaultAuthRef: {{ include "llamator-mcp.fullname" . }}-vault-auth
{{- end }}

{{- end }}
{{- end }}

