{{- if .Values.vault.enabled }}
---
# ExternalSecret for OpenAI API Keys
# Creates a Kubernetes Secret from Vault using External Secrets Operator
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "llamator.fullname" . }}-openai-es
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "llamator.labels" . | nindent 4 }}
spec:
  # How often to sync secrets from Vault
  refreshInterval: {{ .Values.vault.refreshInterval | default "1m" }}

  # Reference to SecretStore or ClusterSecretStore
  secretStoreRef:
    kind: {{ .Values.vault.secretStoreKind | default "ClusterSecretStore" }}
    name: {{ .Values.vault.secretStoreRef | default "vault-backend" }}

  # Target Kubernetes Secret configuration
  target:
    name: {{ .Values.openai.attack.secret.name }}
    creationPolicy: Owner

  # Map Vault secret to Kubernetes Secret keys
  # All three keys use the same OPENAI_API_KEY from Vault
  data:
    # Attack model API key
    - secretKey: {{ .Values.openai.attack.secret.key }}
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: {{ .Values.openai.attack.secret.key | default .Values.vault.openaiKeyProperty }}

    # Judge model API key
    - secretKey: {{ .Values.openai.judge.secret.key }}
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: {{ .Values.openai.judge.secret.key | default .Values.vault.openaiKeyProperty }}

    # Target model API key
    - secretKey: {{ .Values.openai.target.secret.key }}
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: {{ .Values.openai.target.secret.key | default .Values.vault.openaiKeyProperty }}
{{- end }}

